include: '.test.yml'

stages:
  - build


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"


build:
  stage: build
  tags:
    - testy-tagy
  image: library/oraclelinux:9
  artifacts:
    paths: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "test"
    - echo "test2"

test:
  extends: .tester
